### ISSUE TITLE
Add a game icon? [enhancement]

### ISSUE THREAD

**Issue by SofyUchiha** [Fewnity/T-Rex-Runner-Game-Nintendo-DS#2]
Can you add a custom icon for the DS game? (instead of the generic DS HB icon)

Something like this:
![image](https://user-images.githubusercontent.com/70182567/142714060-210fa25d-fd6b-4614-ac8c-25fd56b516ba.png)

I think it would be much better! 
Thank you very much for your creation! I loved it <3

**Comment by Fewnity** [comment]
Done! Thanks for this request!
